# Generated by Django 3.0.7 on 2020-06-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buggernaut', '0002_auto_20200627_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projectImages/img.png', null=True, upload_to='projectImages/'),
        ),
    ]
