# Generated by Django 3.0.7 on 2020-06-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buggernaut', '0003_auto_20200629_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projectImages/img.png', upload_to='projectImages/'),
        ),
    ]
