# Generated by Django 3.0.7 on 2020-06-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buggernaut', '0004_auto_20200629_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='buggernaut.Tag'),
        ),
    ]
